import React, { useState } from 'react';
import { Save, X } from 'lucide-react';
import { adminText } from '../../data/adminTranslations';
import { useBilingualAutoTranslate } from '../../hooks/useBilingualAutoTranslate';
import { useArchive } from '../../context/ArchiveContext';
import { OralHistoryRecordItem, ResearchStatus, RightsStatus, WorkflowStatus } from '../../types';
import { saveOralHistoryRecord } from '../../services/dbService';
import { RESEARCH_CATEGORIES, RESEARCH_STATUS_LABELS, RIGHTS_STATUS_LABELS, WORKFLOW_STATUS_LABELS } from '../../data/archiveData';

interface Props { initialItem?: OralHistoryRecordItem | null; onSuccess: () => void; onCancel: () => void; }

const fieldClass = 'w-full rounded-xl border border-stone-200 bg-white px-3 py-2.5 text-sm outline-none transition focus:border-amber-700 focus:ring-2 focus:ring-amber-100';
const labelClass = 'mb-1.5 block text-xs font-semibold uppercase tracking-wide text-stone-600';

const OralHistorySection: React.FC<{title:string; children:React.ReactNode}> = ({title,children}) => (
  <section className="rounded-2xl border border-stone-200 bg-stone-50/60 p-5 sm:p-6 space-y-4">
    <h3 className="border-b border-stone-200 pb-3 text-sm font-bold tracking-wide text-stone-900">{title}</h3>
    {children}
  </section>
);

export const AdminOralHistoryForm: React.FC<Props> = ({ initialItem, onSuccess, onCancel }) => {
  const { language } = useArchive();
  const [data, setData] = useState<Partial<OralHistoryRecordItem>>(() => initialItem || ({
    id: `oral-${Date.now()}`, title: '', nepaliTitle: '', englishTitle: '', category: 'oral_history', subject: '', community: '',
    informantName: '', informantAge: '', informantRole: '', informantOrigin: '', informantLocation: '', language: '',
    interviewDate: '', interviewLocation: '', interviewer: '', recorder: '', recordingType: '', duration: '', recordingReference: '',
    transcript: '', translation: '', historicalPeriod: '', placesMentioned: '', peopleMentioned: '', testimony: '', researcherNotes: '',
    documentaryEvidence: '', supportingSources: '', evidenceDetails: '', verificationStatus: 'further_research', contradictions: '',
    consentStatus: 'pending', rightsHolder: '', publicationPermission: '', privacyRestrictions: '', copyrightNotes: '', sourceDonor: '',
    referenceId: '', workflowStatus: 'draft', rightsStatus: 'oral_history_permission', createdAt: new Date().toISOString()
  }));
  const [error, setError] = useState('');
  const { setPrimary: setTitleAuto, setSecondary: setNepaliTitle } = useBilingualAutoTranslate(data, setData, 'title', 'nepaliTitle');
  const setEnglishDisplayTitle = (value: string) => {
    setData(prev => ({ ...prev, title: value, englishTitle: value }));
    setTitleAuto(value);
  };
  const set = (key: keyof OralHistoryRecordItem, value: string) => setData(prev => ({ ...prev, [key]: value }));
  const submit = async (e: React.FormEvent) => {
    e.preventDefault(); setError('');
    if (!data.title?.trim() || !data.informantName?.trim() || !data.interviewer?.trim() || !data.testimony?.trim()) {
      setError(adminText(language, 'शीर्षक, सूचनादाता, अन्तर्वार्ताकार र मुख्य मौखिक साक्ष्य अनिवार्य छन्।')); return;
    }
    try {
      await saveOralHistoryRecord({ ...data, id: data.id!, title: data.title!, category: data.category || 'oral_history', informantName: data.informantName!, interviewer: data.interviewer!, testimony: data.testimony!, verificationStatus: (data.verificationStatus || 'further_research') as ResearchStatus, workflowStatus: (data.workflowStatus || 'draft') as WorkflowStatus, rightsStatus: (data.rightsStatus || 'oral_history_permission') as RightsStatus, createdAt: data.createdAt || new Date().toISOString(), updatedAt: new Date().toISOString() } as OralHistoryRecordItem);
      onSuccess();
    } catch { setError(adminText(language, 'मौखिक इतिहास सुरक्षित गर्न असफल भयो। प्रशासक प्रमाणीकरण जाँच गर्नुहोस्।')); }
  };
  return <form onSubmit={submit} className="space-y-5 rounded-3xl border border-stone-200 bg-white p-4 shadow-sm sm:p-7">
    <div className="flex flex-col gap-3 border-b border-stone-200 pb-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.22em] text-amber-800">{adminText(language, 'ORAL HISTORY ARCHIVE')}</p><h2 className="font-serif-np text-2xl font-bold text-stone-900">{adminText(language,'व्यावसायिक मौखिक इतिहास अभिलेख')}</h2><p className="mt-1 text-xs text-stone-500">{adminText(language,'सूचनादाता, अन्तर्वार्ता, साक्ष्य, सहमति र अनुसन्धान audit सहितको structured record')}</p></div><div className="flex gap-2"><button type="button" onClick={onCancel} className="rounded-xl border border-stone-300 px-4 py-2 text-xs font-semibold">{adminText(language,'रद्द गर्नुहोस्')}</button><button type="submit" className="flex items-center gap-2 rounded-xl bg-stone-900 px-4 py-2 text-xs font-semibold text-white"><Save className="h-4 w-4"/>{adminText(language,'अभिलेख सुरक्षित गर्नुहोस्')}</button></div></div>
    {error && <div className="rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-800">{error}</div>}
    <OralHistorySection title={adminText(language,'01 · Identity & Classification')}><div className="grid gap-4 md:grid-cols-2"><label><span className={labelClass}>{adminText(language,'English Title *')}</span><input className={fieldClass} value={data.title||''} onChange={e=>setEnglishDisplayTitle(e.target.value)} required autoComplete="off"/></label><label><span className={labelClass}>{adminText(language,'नेपाली शीर्षक (Auto / Editable)')}</span><input className={fieldClass} value={data.nepaliTitle||''} onChange={e=>setNepaliTitle(e.target.value)} autoComplete="off"/></label><label><span className={labelClass}>{adminText(language,'Category')}</span><select className={fieldClass} value={data.category||'oral_history'} onChange={e=>set('category',e.target.value)}>{RESEARCH_CATEGORIES.map(c=><option key={c.key} value={c.key}>{language==='ne'?c.nepali:c.english}</option>)}</select></label><label><span className={labelClass}>{adminText(language,'Subject / Topic')}</span><input className={fieldClass} value={data.subject||''} onChange={e=>set('subject',e.target.value)}/></label><label><span className={labelClass}>{adminText(language,'Community')}</span><input className={fieldClass} value={data.community||''} onChange={e=>set('community',e.target.value)}/></label></div></OralHistorySection>
    <OralHistorySection title={adminText(language,'02 · Informant & Interview')}><div className="grid gap-4 md:grid-cols-2"><label><span className={labelClass}>{adminText(language,'Informant / सूचनादाता *')}</span><input className={fieldClass} value={data.informantName||''} onChange={e=>set('informantName',e.target.value)} required/></label><label><span className={labelClass}>{adminText(language,'Age / उमेर')}</span><input className={fieldClass} value={data.informantAge||''} onChange={e=>set('informantAge',e.target.value)}/></label><label><span className={labelClass}>{adminText(language,'Role / Occupation')}</span><input className={fieldClass} value={data.informantRole||''} onChange={e=>set('informantRole',e.target.value)}/></label><label><span className={labelClass}>{adminText(language,'Origin / Ancestral Place')}</span><input className={fieldClass} value={data.informantOrigin||''} onChange={e=>set('informantOrigin',e.target.value)}/></label><label><span className={labelClass}>{adminText(language,'Interview Date')}</span><input type="date" className={fieldClass} value={data.interviewDate||''} onChange={e=>set('interviewDate',e.target.value)}/></label><label><span className={labelClass}>{adminText(language,'Interview Location')}</span><input className={fieldClass} value={data.interviewLocation||''} onChange={e=>set('interviewLocation',e.target.value)}/></label><label><span className={labelClass}>{adminText(language,'Interviewer / Collector *')}</span><input className={fieldClass} value={data.interviewer||''} onChange={e=>set('interviewer',e.target.value)} required/></label><label><span className={labelClass}>{adminText(language,'Recorder / Videographer')}</span><input className={fieldClass} value={data.recorder||''} onChange={e=>set('recorder',e.target.value)}/></label></div></OralHistorySection>
    <OralHistorySection title={adminText(language,'03 · Recording, Transcript & Context')}><div className="grid gap-4 md:grid-cols-2"><label><span className={labelClass}>{adminText(language,'Recording Type')}</span><input className={fieldClass} placeholder={language === 'ne' ? 'अडियो / भिडियो / फिल्ड नोट' : 'Audio / Video / Field notes'} value={data.recordingType||''} onChange={e=>set('recordingType',e.target.value)}/></label><label><span className={labelClass}>{adminText(language,'Duration')}</span><input className={fieldClass} value={data.duration||''} onChange={e=>set('duration',e.target.value)}/></label><label><span className={labelClass}>{adminText(language,'Historical Period')}</span><input className={fieldClass} value={data.historicalPeriod||''} onChange={e=>set('historicalPeriod',e.target.value)}/></label><label><span className={labelClass}>{adminText(language,'Recording / Media Reference')}</span><input className={fieldClass} value={data.recordingReference||''} onChange={e=>set('recordingReference',e.target.value)}/></label><label className="md:col-span-2"><span className={labelClass}>{adminText(language,'मुख्य मौखिक साक्ष्य / Testimony *')}</span><textarea className={fieldClass} rows={5} value={data.testimony||''} onChange={e=>set('testimony',e.target.value)} required/></label><label><span className={labelClass}>{adminText(language,'Transcript')}</span><textarea className={fieldClass} rows={4} value={data.transcript||''} onChange={e=>set('transcript',e.target.value)}/></label><label><span className={labelClass}>{adminText(language,'Translation')}</span><textarea className={fieldClass} rows={4} value={data.translation||''} onChange={e=>set('translation',e.target.value)}/></label></div></OralHistorySection>
    <OralHistorySection title={adminText(language,'04 · Evidence & Verification')}><div className="grid gap-4 md:grid-cols-2"><label><span className={labelClass}>{adminText(language,'Documentary Evidence')}</span><textarea className={fieldClass} rows={3} value={data.documentaryEvidence||''} onChange={e=>set('documentaryEvidence',e.target.value)}/></label><label><span className={labelClass}>{adminText(language,'Supporting Sources')}</span><textarea className={fieldClass} rows={3} value={data.supportingSources||''} onChange={e=>set('supportingSources',e.target.value)}/></label><label className="md:col-span-2"><span className={labelClass}>{adminText(language,'Evidence Details')}</span><textarea className={fieldClass} rows={3} value={data.evidenceDetails||''} onChange={e=>set('evidenceDetails',e.target.value)}/></label><label><span className={labelClass}>{adminText(language,'Verification Status')}</span><select className={fieldClass} value={data.verificationStatus||'further_research'} onChange={e=>set('verificationStatus',e.target.value)}>{Object.entries(RESEARCH_STATUS_LABELS).map(([k,v])=><option key={k} value={k}>{language==='ne'?v.nepali:v.english}</option>)}</select></label><label><span className={labelClass}>{adminText(language,'Contradictions / Further Questions')}</span><textarea className={fieldClass} rows={3} value={data.contradictions||''} onChange={e=>set('contradictions',e.target.value)}/></label></div></OralHistorySection>
    <OralHistorySection title={adminText(language,'05 · Consent, Rights & Preservation')}><div className="grid gap-4 md:grid-cols-2"><label><span className={labelClass}>{adminText(language,'Consent Status')}</span><select className={fieldClass} value={data.consentStatus||'pending'} onChange={e=>set('consentStatus',e.target.value)}><option value="pending">{language === 'ne' ? 'प्रतीक्षामा' : 'Pending'}</option><option value="documented">{language === 'ne' ? 'सहमति अभिलेखित' : 'Documented Consent'}</option><option value="restricted">{language === 'ne' ? 'सीमित' : 'Restricted'}</option><option value="not_required">{language === 'ne' ? 'आवश्यक छैन' : 'Not Required'}</option></select></label><label><span className={labelClass}>{adminText(language,'Rights Holder')}</span><input className={fieldClass} value={data.rightsHolder||''} onChange={e=>set('rightsHolder',e.target.value)}/></label><label><span className={labelClass}>{adminText(language,'Publication Permission')}</span><input className={fieldClass} value={data.publicationPermission||''} onChange={e=>set('publicationPermission',e.target.value)}/></label><label><span className={labelClass}>{adminText(language,'Privacy Restrictions')}</span><input className={fieldClass} value={data.privacyRestrictions||''} onChange={e=>set('privacyRestrictions',e.target.value)}/></label><label className="md:col-span-2"><span className={labelClass}>{adminText(language,'Copyright / Usage Notes')}</span><textarea className={fieldClass} rows={3} value={data.copyrightNotes||''} onChange={e=>set('copyrightNotes',e.target.value)}/></label></div></OralHistorySection>
    <OralHistorySection title={adminText(language,'06 · Research & Publication Audit')}><div className="grid gap-4 md:grid-cols-2"><label><span className={labelClass}>{adminText(language,'Source / Donor')}</span><input className={fieldClass} value={data.sourceDonor||''} onChange={e=>set('sourceDonor',e.target.value)}/></label><label><span className={labelClass}>{adminText(language,'Archive Reference ID')}</span><input className={fieldClass} value={data.referenceId||''} onChange={e=>set('referenceId',e.target.value)}/></label><label><span className={labelClass}>{adminText(language,'Workflow Status')}</span><select className={fieldClass} value={data.workflowStatus||'draft'} onChange={e=>set('workflowStatus',e.target.value)}>{Object.entries(WORKFLOW_STATUS_LABELS).map(([k,v])=><option key={k} value={k}>{language==='ne'?v.nepali:v.english}</option>)}</select></label><label><span className={labelClass}>{adminText(language,'Rights Status')}</span><select className={fieldClass} value={data.rightsStatus||'oral_history_permission'} onChange={e=>set('rightsStatus',e.target.value)}>{Object.entries(RIGHTS_STATUS_LABELS).map(([k,v])=><option key={k} value={k}>{language==='ne'?v.nepali:v.english}</option>)}</select></label></div></OralHistorySection>
  </form>;
};
